### ISSUE TITLE
UI FIX NEEDED FOR QUERY PAGE

### ISSUE THREAD

**Issue by adityassharma-ss** [adityassharma-ss/answerme#10]
Fix the query submission page

**Comment by joshijoe05** [comment]
Can you elaborate the issue and provide some screenshots

**Comment by adityassharma-ss** [comment]
![AnswerMe - Brave 10_3_2023 12_14_48 AM](https://github.com/adityassharma-ss/answerme/assets/82082352/00cf3e4f-efbb-4e7f-bd97-5a971a397a5d)

This portion's design needs to be improved to make it more attractive.

**Comment by Harrshhpattell** [comment]
i want to work on this issue. Can u assign me

**Comment by adityassharma-ss** [comment]
Done

**Comment by Harrshhpattell** [comment]
Do you have a particular design in mind, or should I create one based on my own preferences

**Comment by adityassharma-ss** [comment]
You can implement your own ideas.

**Comment by Harrshhpattell** [comment]
I've designed the query page. Please take a look, and if you have any questions or suggestions for redesigning anything, feel free to let me know.

![image](https://github.com/adityassharma-ss/answerme/assets/102842153/1f71f4c3-3691-4cec-bb82-f305629f5339)

**Comment by adityassharma-ss** [comment]
can you change the buttons as well? It will be appreciated.

**Comment by Harrshhpattell** [comment]
sure

**Comment by Harrshhpattell** [comment]
![image](https://github.com/adityassharma-ss/answerme/assets/102842153/58ac911e-9dcd-4ff0-a3ac-ac55270df4b7)
hover effect 👇👇
![image](https://github.com/adityassharma-ss/answerme/assets/102842153/47c038b7-692e-48f5-bbf8-a8461c098f21)
-----------------------------------------------------
![image](https://github.com/adityassharma-ss/answerme/assets/102842153/936d6b94-f2ec-418c-81dd-d73b378d98b2)
hover effect 👇👇
![image](https://github.com/adityassharma-ss/answerme/assets/102842153/82f5e400-6a8a-4bd6-8568-3440074c8471)

**Comment by Harrshhpattell** [comment]
done

**Comment by Harrshhpattell** [comment]
This issue has been fixed. Closing.

**Comment by Harrshhpattell** [comment]
Fixes #10

Unfortunately, I don't have the necessary permissions to close this issue.
I kindly request to close it.
