### ISSUE TITLE
Responsive navbar and footer 

### ISSUE THREAD

**Issue by Harrshhpattell** [adityassharma-ss/answerme#11]
I'm ready to work on  making the UI responsive with a burger-menu and some changes to footer for Mobile view.

**Comment by adityassharma-ss** [comment]
Assigning it to you.

**Comment by Harrshhpattell** [comment]
I've made some updates to the navigation and footer components to make them responsive and user-friendly. The changes ensure that the website looks great on various screen sizes, from desktop to mobile devices.

I've thoroughly tested these updates, but I'm open to feedback and willing to make any further adjustments or improvements if needed. Please feel free to share your thoughts, and I'll be excited to work on them!

Let me know if there's anything else I can do to help with these changes. Thanks for considering my contribution! 🚀
