### ISSUE TITLE
Improve Docs Page Design with CSS Enhancements

### ISSUE THREAD

**Issue by Harrshhpattell** [adityassharma-ss/answerme#14]
The docs page of the project currently lacks a polished and visually appealing design. 

I would like to take the initiative to enhance the design of the docs page.

**Comment by adityassharma-ss** [comment]
Assigning it to you.

**Comment by Harrshhpattell** [comment]
Hi there,

I've made some improvements to the documentation page. The changes should make the documentation more readable and organized. Please review and let me know if any further adjustments are needed.

Thanks!
