### ISSUE TITLE
New enhanced UI needed

### ISSUE THREAD

**Issue by adityassharma-ss** [adityassharma-ss/answerme#7]
This repo is open to accept new UI ideas for this project

**Comment by anubhav1206** [comment]
There are a lot of things that can be done:
1. Buttons can be made smaller and interactive
2. Clicking on the "Get Started" button scrolls you directly to the form
3. Use of more colours in the site
Let me know if you want any of the above features implemented!

**Comment by adityassharma-ss** [comment]
You can add them. Just don't forget to add the screenshot of your work if you raise any PR.

**Comment by anubhav1206** [comment]
> You can add them. Just don't forget to add the screenshot of your work if you raise any PR.

Sure!

**Comment by adityassharma-ss** [comment]
Home page UI is fixed
